---
title: "About"
author: "Tate Huffman"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About

There's more data in baseball than ever now. Whether you're interested in the probability a Mike Trout line drive will fall for a hit, the top speed Ronald Acuña Jr. reaches going from first to third, or the precise arm slot at which Josh Hader releases each fastball, these measurements are all available at quite literally the push of a button. Yet with the game becoming viewed by many as a series of sequences and estimations, there remain questions about what hasn't yet been quantified. Some of it is, of course, not truly measurable - one can't reduce a great teammate's impact on the clubhouse to fractions of a win or assess how many points of stolen base percentage a savvy first-base coach might add - but there's still room to improve analysis in certain areas. One of these is pitch sequencing: how to optimize variation in pitch type, speed, and location.

In order to be able to properly analyze the effects of pitch sequencing, pitch-level MLB data is of course required. Thankfully, when MLB introduced Statcast, its player-tracking camera system, in 2015, they made all the data publicly available and accessible via [Baseball Savant](https://baseballsavant.mlb.com), and for this project I collected it using Bill Petti's immensely useful [baseballr package](http://billpetti.github.io/baseballr/). The past two years of data have been found to be more accurate than 2015-2017, but because we're primarily interested in basic pitch data and less so more advanced metrics like spin rate and exit velocity, I feel comfortable using all available Statcast measurements. In order to properly handle the multiple gigabytes worth of data, I used Git LFS and a modified form of Petti's `scrape_statcast_savant` function in order to get the full five regular seasons of data.

#### [Link to GitHub Repository](https://github.com/tjhuffman4246/finalproject_initial)