---
title: "Explore"
author: "Tate Huffman"
date: "3/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
library(baseballr)
library(lubridate)
library(gt)
library(tidyverse)
```

## Looking at Our Data

```{r load_info}

# replicating function from gather.Rmd to load in data
# creates function to load in these files, via below Stack Overflow thread:
# https://stackoverflow.com/questions/23190280/
# whats-wrong-with-my-function-to-load-multiple-csv-files-into-single-dataframe

load_files <- function(path) { 
  files <- dir(path, pattern = "data_\\d{4}.csv", full.names = TRUE)
  bind_rows(map_df(files, read_csv))
}

# loads in all files in this directory and combines into single dataframe

pitches <- load_files("data")

```

We replicate some of the code from previous work in order to load in the multiple gigabytes of pitch data we've gathered since the start of the 2015 season. Let's explore how league-wide pitch distributions have evolved over the past five years.

```{r exploration, include = TRUE, echo = FALSE}

# looking at how the percent of different pitches has evolved over time
# let's first get the number of pitches in a given year into a new tibble

yearly_npitch <- pitches %>% 
  group_by(year(game_date)) %>% 
  summarize(count = n()) %>% 
  rename(year = "year(game_date)")

# for-loop iterates over each year and gets pitch distribution for each year
# uses lubridate package to get the year for each game
# each table shows the top five most frequently thrown pitches
# paste function enables use of year input variable in column title

yearly_pitchdistr <- function(yr) {
  pitches %>%
    filter(year(game_date) == yr) %>% 
    group_by(pitch_name) %>% 
    summarize(percent = n() / pull(filter(yearly_npitch, year == yr), count)) %>%
    mutate(percent = 100 * round(percent, 4)) %>% 
    arrange(desc(percent))
} 

# gets yearly pitch distribution and joins into one dataframe
# combines these pitch distributions into a list and joins by pitch name

distr_2019 <- yearly_pitchdistr(2019)
distr_2018 <- yearly_pitchdistr(2018)
distr_2017 <- yearly_pitchdistr(2017)
distr_2016 <- yearly_pitchdistr(2016)
distr_2015 <- yearly_pitchdistr(2015)

distr_combined <- list(distr_2015, distr_2016, distr_2017, 
                       distr_2018, distr_2019) %>% 
  reduce(inner_join, by = "pitch_name") %>% 
  rename(percent_2015 = "percent.x",
         percent_2016 = "percent.y", 
         percent_2017 = "percent.x.x",
         percent_2018 = "percent.y.y",
         percent_2019 = "percent")

# Table time!

distr_combined %>% 
  gt() %>% 
  tab_header(title = "MLB Pitch Distribution, 2015-2019",
             subtitle = "Percent of All Pitches Thrown") %>% 
  cols_label(pitch_name = "Pitch Type", 
             percent_2015 = "2015",
             percent_2016 = "2016",
             percent_2017 = "2017",
             percent_2018 = "2018", 
             percent_2019 = "2019") %>% 
  tab_footnote(footnote = "Data via Baseball Savant", 
               locations = cells_title())

```
