---
title: "Model"
author: "Tate Huffman"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
library(magrittr)
library(tidyverse)
```

## Building the Model

We want to examine the effect of pitch sequencing on pitcher success - or to see whether it has a substantial effect at all. We load in our data, and create new variables, using code from previous Rmarkdown documents. 

```{r load_data, cache = TRUE}

# copying and altering most of code from explore.Rmd

load_files <- function(path) { 
  files <- dir(path, pattern = "data_\\d{4}.csv", full.names = TRUE)
  bind_rows(map_df(files, read_csv))
}

pitches <- load_files("data")

# creates pitch sequence

pitches %<>% mutate(pitch_seq = ifelse(!(pitch_number == 1 |
                                        is.na(pitch_type) |
                                        is.na(lag(pitch_type))), 
                                      paste0(lag(pitch_type), pitch_type),
                                      NA))

# adds in batter names, manually inputting unknown players

players <- read_csv("players.csv", col_types = cols()) %>% 
  select(mlb_id, mlb_name)

pitches %<>% 
  left_join(players, by = c("batter" = "mlb_id")) %>% 
  rename(batter_name = "mlb_name", pitcher_name = "player_name") %>% 
  mutate(batter_name = case_when(batter == 121347 ~ "Alex Rodriguez",
                                 batter == 116338 ~ "Torii Hunter",
                                 batter == 133380 ~ "Aramis Ramirez",
                                 batter == 120074 ~ "David Ortiz",
                                 batter == 150229 ~ "A.J. Pierzynski",
                                 batter == 218596 ~ "Tim Hudson",
                                 batter == 150359 ~ "A.J. Burnett",
                                 batter == 150302 ~ "Jason Marquis",
                                 batter == 329092 ~ "Randy Choate",
                                 batter == 279824 ~ "Mark Buehrle",
                                 batter == 605228 ~ "Jose Fernandez",
                                 batter == 115629 ~ "LaTroy Hawkins",
                                 TRUE ~ as.character(batter_name)))

# adding more pitch info in comparison to previous pitches

pitches %<>% 
  mutate(speed_diff = ifelse(!(pitch_number == 1 | 
                                 is.na(pitch_type) | 
                                 is.na(lag(pitch_type))),
                             release_speed - lag(release_speed), NA),
         loc_diff_x = ifelse(!(pitch_number == 1 | 
                                 is.na(pitch_type) | 
                                 is.na(lag(pitch_type))),
                             plate_x - lag(plate_x), NA),
         loc_diff_z = ifelse(!(pitch_number == 1 | 
                                 is.na(pitch_type) | 
                                 is.na(lag(pitch_type))),
                             plate_z - lag(plate_z), NA),
         loc_diff_total = ifelse(!(pitch_number == 1 | 
                                     is.na(pitch_type) | 
                                     is.na(lag(pitch_type))),
                                 sqrt(loc_diff_x^2 + loc_diff_z^2), NA))

# create binary indicator for whether pitcher was the starter

pitches %<>% 
  group_by(game_pk, inning_topbot) %>% 
  mutate(starter = ifelse(pitcher_name == first(pitcher_name), 1, 0)) %>% 
  ungroup()

# creates a smaller sample dataset w/ data from random 1,000 games

pitch_sample <- pitches %>% 
  filter(game_pk %in% c(sample(pull(select(pitches, game_pk)), 1000)))

```



